name: g_kit
publish_to: 'none'
environment:
  sdk: '>=3.6.0 <4.0.0'
resolution: workspace
packages:
  - g_lib
  - g_common
  - g_core
  - g_model
  - g_plugin
  - g_ui
  
scripts:
  bootstrap:
    run: melos bootstrap --scope="g_*"
  analyze:
    run: melos exec -- flutter analyze
  get:
    run: melos exec -- flutter pub get
  test:
    run: melos exec -- flutter test
  outdated:
    run: melos exec -- flutter pub outdated
  generate:
    run: melos exec --depends-on build_runner -- dart run build_runner build --delete-conflicting-outputs
  build_apk:
    run: melos exec --dir-exists=android -- flutter build apk
  build_ios:
    run: melos exec --dir-exists=ios -- flutter build ios
  clean:
    run: melos exec -- flutter clean
  clean-all:
    run: melos clean
  clean-cache:
    run: melos exec -- flutter pub cache clean
  # Git 관련 명령어들
  git-status:
    run: git status
  git-add:
    run: git add .
  git-commit:
    run: ./scripts/git_commit.sh
  git-commit-push:
    run: ./scripts/git_commit.sh --push
  git-push:
    run: git push
  git-pull:
    run: git pull
  git-log:
    run: git log --oneline -10
  git-diff:
    run: git diff --cached
  git-stash:
    run: git stash
  git-stash-pop:
    run: git stash pop
  git-commit-hash:
    run: git rev-parse HEAD
