name: g_plugin
description: "A new Flutter plugin project."
version: 0.0.1
homepage: 'https://github.com/appify/g_kit'
repository: 'https://github.com/appify/g_kit'
publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

  g_common:
    path: ../g_common

  g_lib:
    path: ../g_lib
  
  g_model:
    path: ../g_model

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: app.appify.g_plugin
        pluginClass: GPlugin
      ios:
        pluginClass: GPlugin
      macos:
        pluginClass: GPlugin
      windows:
        pluginClass: GPluginCApi