name: g_plugin
description: "A new Flutter plugin project."
version: 0.0.1
homepage: 'https://github.com/appify/g_kit'
repository: 'https://github.com/appify/g_kit'
publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  workmanager: ^0.9.0+3

  g_common:
    git:
      url: git@github.com:Asran-lab/g_kit.git
      path: g_common
      ref: main

  g_lib:
    git:
      url: git@github.com:Asran-lab/g_kit.git
      path: g_lib
      ref: main
  
  g_model:
    git:
      url: git@github.com:Asran-lab/g_kit.git
      path: g_model
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: app.appify.g_plugin
        pluginClass: GPlugin
      ios:
        pluginClass: GPlugin
      macos:
        pluginClass: GPlugin
      windows:
        pluginClass: GPluginCApi